### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jrzubizarreta** [ccb-hms/designmatch_docker#5]
Under About (on the top right corner of the page), could we please edit as follows?
•	“A Docker one-and-done approach to easily install and work with the designmatch package and the Gurobi optimizer in R.” 

Under README.md, could we please edit as follows?
•	Title: “designmatch dockerized” (No caps and no hyphens please.)
•	Description: “A Docker one-and-done approach to easily install and work with the designmatch package and the Gurobi optimizer in R.” 
•	About the Project: “About the Project” (No caps on “the” please.)
•	About the Project: “This project was created simplify the installation and use of the designmatch package for R, without separately installing the required libraries and dependencies. This project is a collaboration between the Center for Computational Biomedicine (CCB) and Department of Health Care Policy (HCP) at Harvard Medical School.”

Under Installation, could we please modify as follows?
•	Change “Installation” for “Installing designmatch and its dependencies”.
•	Remove the note (“**Note: If this is NOT your first time using this repository, you can skip to step 7. **” ) and have a separate section with step 7 titled “Using designmatch”.
•	Many users of designmatch will not know what a “repo” is, a “base directory,” or what exactly means “cloning,” so I would suggest editing step 1 as follows: “Select a working directory, open a terminal, and execute the following command”
•	Step 2: “Go to https://pages.gurobi.com/registration/ to register for an Academic License of Gurobi Optimizer.
•	It would seem that Step 4 needs more guidance because after clicking on “DOWNLOAD” one is asked, “An API Key has already been created for license 691223. Are you sure you want to create a new one?”. I understand that the answer is Yes, i.e., to “CREATE NEW API KEY,” but I’m not sure. It could help some users to anticipate these questions.
•	Step 5: on Step 1 I already opened a terminal. Does one need to open another terminal? Also, how can I ensure that Docker is running? 
•	Step 6: do I need to include the dot at the end of the command? 

I get the following message: “-bash: docker: command not found”, so I can’t continue. 

Another question, is there a way to count the number of users through time?

**Comment by sam-pullman** [comment]
Hi Jose, your comments have been integrated. Please try to follow the instructions and let me know if you have any further requests. Thanks!
